name: test

on:
  [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-image: [7.1]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file ./${{ matrix.php-image}}/Dockerfile --tag=fgch/php-fpm-informix:${{ matrix.php-image }}

      - name: Create Testnetwork
        run: docker network create test-network

      - name: Start Informix server
        run: docker run -td --name ifx-test -h ifx --network=test-network -e LICENSE=accept -e STORAGE=local -p 9088:9088 -p 9089:9089 -p 27017:27017 -p 27018:27018 -p 27883:27883 fgch/informix-test:14.10.FC5IE

      - name: Wait for the database
        run: sleep 20

      - name: Run tests
        run: docker run --rm -v $(pwd)/.github/workflows/:/app --network=test-network fgch/php-fpm-informix:${{ matrix.php-image }} php /app/tests.php

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fgch/php-fpm-informix:latest
